services:
  - type: web
    name: bsnl-complaint-portal
    env: static
    buildCommand: echo "Building static site..." && ls -la
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /home.html
    envVars:
      - key: NODE_ENV
        value: production
