services:
  - type: web
    name: bsnl-complaint-portal
    env: static
    buildCommand: echo "Building static site..." && ls -la
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          - name: X-Frame-Options
            value: DENY
          - name: X-Content-Type-Options
            value: nosniff
          - name: Referrer-Policy
            value: strict-origin-when-cross-origin
          - name: Permissions-Policy
            value: "geolocation=(), microphone=(), camera=()"
    envVars:
      - key: NODE_ENV
        value: production
